### ISSUE TITLE
Nouveau Projet Java

### ISSUE THREAD

**Issue by Ricorei** [KralandCE/krapi-core#1]
Il nous faut un projet java simple ( intellij ou eclipse ) mais sans les fichiers de configurations.
On peux choisir un système de build ( gradle ou maven ) ou de laisser les librairies importées à la main.

**Comment by Hello-Gitty** [comment]
Moi je préfère Maven.
Le plus "urgent" c'est de faire le parser d'évènements.

A voir la structure de base de donnée pour la sauvegarde.

**Comment by Maelstrom18** [comment]
Je ne suis pas expert du java web, mais à chaque fois que j'en ai fait c'était avec Maven et Eclipse.

**Comment by Ricorei** [comment]
Va pour Maven.
Je suis toujours sous Intellij, donc n'oubliez pas de mettre vos fichiers de configurations eclipses sous .gitignore.

**Comment by Hello-Gitty** [comment]
Demain soir, j'essaye de pousser un projet pour parser les évènements.
Ce sera un squelette, en repartant sur quelques classe que j'avais pour le faire.

Niveau repo, on met tout dans krapi ? ou on fait un repo à côté pour les parser ?

**Comment by Ricorei** [comment]
Tu peux mettre ton ancien code dans un package old ou migration. Ça fera moins de bazar. Tant que ça n’empêche pas la compilation.
Si tu parles des données que l'API va générer, je pense qu'on ne les mettra pas sous github. Faudra se contenter d'une copie locale et de déployer le code en production.

**Comment by hari-mak-enji** [comment]
Maven et IntelliJ pour moi aussi ça m'arrange.
Pour la Bdd on part sur du "standard" ? Ou une petite base mongo pour stocker les évents ça s'y prêterait bien.

**Comment by Ricorei** [comment]
Il n'y aura pas de bdd pour ce dépôt.
Je vais mettre à jour le Wiki.

**Comment by Hello-Gitty** [comment]
J'ai poussé comme j'avais dis.
C'est le début, J'arrive à me loguer avec un compte slave.
Récupéré les cookies, j'ai l'algo en tête, mais pour le moment je me heurt à KI qui me jette pour action externe.

Je vais avancer doucement sur le sujet.

On va dire c'est les premiers pas.

**Comment by Ricorei** [comment]
C'est vu, merci !
Si tu n'as rien d'autre à préciser pour ce ticket, je te laisse le fermer.

**Comment by Hello-Gitty** [comment]
Je le fermerais pour marquer la fin du dev effectif de la récupération des evenements.
Possible que je continue après les dev pour le rendre propre, si je ne le fais pas directement. Mais comme ça la fermeture du ticket servira de jalon pour informer tous le monde que c'est fonctionnel.

Sauf si tu as prévu/vu un autre process, mais ça me semble bien, suffisamment léger pour la taille du projet.

**Comment by Ricorei** [comment]
il faut rester avec un ticket par tâche.
Si tu souhaites ouvrir une discussion globale, ouvre en une à part.

**Comment by Hello-Gitty** [comment]
Infos sur l'avancé du parser.
Reste: 
-parser proprement les datas pour récupérer les images, lien, etc.
-trouver comment passer la sécurité de kraland (vu que les évènements sont caché, on peut plus tester)
-tester en condition réel l'exploration des pages antérieur pour vérifier que tous les évènements d'une date sont bien récupérés
-nettoyer, passer en constante, structurer quelques éléments

**Comment by Ricorei** [comment]
Tu veux sauvegarder les images ?
Moi je me contentais juste de sauvegarder le code html vu qu'il est composé de peu de balises ( tu peux fournir une white-list qui t'évite les attaques par injection ).

Dans tout les cas pour les images, il faudra faire un module à part histoire d’être compatible avec les restrictions des hébergeurs.

 -trouver comment passer la sécurité de kraland

Haha. C'est sur qu'on est pas aidé pour le coup.

-tester en condition réel l'exploration des pages antérieur

Il y a un cas particulier où un évènement est ajouté pendant que tu es en train de récupérer les pages et que cet évènement en crée une nouvelle.

**Comment by Hello-Gitty** [comment]
> Tu veux sauvegarder les images ?
C'est un abus de langage, c'est bien le html que je veux récupérer. Je ne sais pas si je le conserve tel quel ou si je le transforme en équivalence de code comme sur le forum avec un pseudo bbcode.

>Il y a un cas particulier 
Oui c'est pas totalement sec ma récupération des pages. Et je n'avais pas pensé à ce cas là.

**Comment by Ricorei** [comment]
Ok ok !
Il faudra faire ce module d'image pour la sauvegarde des avatars de toute façon.
Je te conseillerais de garder tout ce que tu peux en raw. Laisse le post traitement aux outils supplémentaires.

**Comment by Ricorei** [comment]
J'ai envoyé un km avec les parsers, tu devrais trouver dedans les solutions qui te manquent ( sécurité KI et gestion des images ).

**Comment by Hello-Gitty** [comment]
J'ai vu, merci.
Dans l'idée c'était la piste que j'envisageais. Simuler les actions sur la page que je récupère, à voir si c'est possible directement avec JSoup.

**Comment by Ricorei** [comment]
Oui c'est possible, mais on ne simule pas un utilisateur, on forge directement une requête POST ou GET dans laquelle on cale les cookies et les variables nécessaires ( d'un formulaire, par exemple ).

**Comment by Ricorei** [comment]
Sinon j'ai vu que tu as un module `ki-event-parser`. Tu comptes avoir d'autres modules ? Comme par exemple `ki-users-parser` ? Comment as-tu prévu la gestion des versions de KI ? Est-ce que tu le gère par module ou globalement ( `ki-data-version` ) ?

Par exemple on a 8 empires actuellement, si on se retrouve avec 5 demain ? Avec 10 ? Comment est-ce qu'on gère le fait qu'on risque d'avoir besoin des empires dans chacun des modules ? Et comment on s'assure de l'intégrité et de la cohérence des données de ce qu'on récupère ( par exemple on fait quoi si on a un bug qui fait que le nom d'un empire/ville/province/joueurs et que ça nous retourne `""` ou `null`  ? Est-ce que `"Empire Brun"` c'est aussi `"empire brun"` ?

**Comment by Hello-Gitty** [comment]
Je ne sais pas encore.

Et bon avec la réouverture je pensais avoir le temps de gérer la sécurité, mais pour le moment ya un truc qui m'échappe pour mes requêtes.

**Comment by Hello-Gitty** [comment]
Au matin ça va mieux, ça avance.
Je pense que ce soir ou demain aprem max j'aurais terminé le parseur d'event.

**Comment by Hello-Gitty** [comment]
C'est pas propre, pour le moment, mais ça marche.
-Faut que je factorise. 
-Ajoute un mode pour choisir la date de capture. 
-Ajout d'un logger
-Un peu de refactoring aussi

**Comment by Hello-Gitty** [comment]
La qualité encore perfectible.
J'ai ajouté une option pour passer des paramètres à la jvm pour remplir les param : -Dkralandce.is.authentification=true -Dkralandce.slave.password=<password> -Dkralandce.slave.login=<login>
J'ai deux modes de capture, soit avec une date soit par défaut J-1

C'est utilisable.

**Comment by Hello-Gitty** [comment]
Refactoré encore pour extraire une lib ki-common contenant les fonctions utilitaires de récupération de page ou de gestion de l'authentification.
