### ISSUE TITLE
Package pour l'organisation

### ISSUE THREAD

**Issue by Ricorei** [KralandCE/krapi-core#14]
Actuellement il y a `org.kraland.community,parser`.
Est-ce qu'on devrait utiliser `org.kralandce.krapi.core.parser` à la place ? Qu´on ai exactement la bonne information en ce qui concerne le projet.

**Comment by Hello-Gitty** [comment]
Oui j'avais mis un truc par défaut.
Je mettrais ça à la place. Sans pb.

Je pousse la modif ce soir.
