### ISSUE TITLE
Parsers additionnels

### ISSUE THREAD

**Issue by Ricorei** [KralandCE/krapi-core#15]
http://www.kraland.org/xml/cit1.xml
http://www.kraland.org/xml/cit2.xml
http://www.kraland.org/xml/cit3.xml
http://www.kraland.org/xml/cit4.xml
http://www.kraland.org/xml/cit5.xml
http://www.kraland.org/xml/cit6.xml
http://www.kraland.org/xml/cit7.xml
http://www.kraland.org/xml/cit8.xml
http://www.kraland.org/xml/list1.xml
http://www.kraland.org/xml/list2.xml
http://www.kraland.org/xml/list3.xml

A savoir qu'ils ne sont mis à jour qu'au travers de la MAJ Kraland, et donc que ces données sont incomplètes vu qu'il n'y a plus de maj depuis le crash. La structure devrait être bonne.

**Comment by Hello-Gitty** [comment]
Parser fait, dispo dans krapi.core.ki-people-parser
