### ISSUE TITLE
Extraction incomplète des évènements

### ISSUE THREAD

**Issue by Ricorei** [KralandCE/krapi-core#19]
J'ai retrouvé ça dans les dumps des événements :  `"data": "\u003ctd class\u003d\"ev_normal\"`
Il faut que le type d'évènement soit un attribut à part entière. Il n'en existe que trois jusqu'à présent : 

- normal
- maj
- anim

**Comment by Hello-Gitty** [comment]
Traité.
J'ai migré les données déjà sauvegardée.
Le code de migration sera supprimé plus tard.
